
package Tela;

public class TelaPrincipal extends javax.swing.JFrame {

   
    
    
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TBrelatorios = new javax.swing.JButton();
        CDlaboratorios = new javax.swing.JButton();
        CDmanutencao = new javax.swing.JButton();
        CDmaquinas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaImagemPrincipal.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tela Principal:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        TBrelatorios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TBrelatorios.setText("Relatórios ");
        TBrelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBrelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(TBrelatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 166, 44));

        CDlaboratorios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CDlaboratorios.setText("Laboratórios");
        CDlaboratorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDlaboratoriosActionPerformed(evt);
            }
        });
        getContentPane().add(CDlaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 183, 44));

        CDmanutencao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CDmanutencao.setText("Manutenção");
        CDmanutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDmanutencaoActionPerformed(evt);
            }
        });
        getContentPane().add(CDmanutencao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 166, 44));

        CDmaquinas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CDmaquinas.setText("Maquinas");
        CDmaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDmaquinasActionPerformed(evt);
            }
        });
        getContentPane().add(CDmaquinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 183, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaImagemPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CDmaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDmaquinasActionPerformed
        TelaMaquina maq1 = new TelaMaquina();
        maq1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CDmaquinasActionPerformed

    private void CDmanutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDmanutencaoActionPerformed
        TelaManutencao manut1 = new TelaManutencao();
        manut1.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_CDmanutencaoActionPerformed

    private void CDlaboratoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDlaboratoriosActionPerformed
        TelaLaboratorio lab1 = new TelaLaboratorio();
        lab1.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_CDlaboratoriosActionPerformed

    private void TBrelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBrelatoriosActionPerformed
        TelaRelatorios rel1 = new TelaRelatorios();
        rel1.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_TBrelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CDlaboratorios;
    private javax.swing.JButton CDmanutencao;
    private javax.swing.JButton CDmaquinas;
    private javax.swing.JButton TBrelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
